// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionType = "HTTP" | "HTTPS" | "SOCKS4" | "SOCKS5" | "SHADOWSOCKS" | "SNELL" | "VMESS" | "VLESS" | "REDIR" | "TPROXY" | "TROJAN" | "TUNNEL" | "TUN" | "TUIC" | "HYSTERIA2" | "ANYTLS" | "MIERU" | "SUDOKU" | "TRUSTTUNNEL" | "INNER" | { "Unknown": string };
