// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleType } from "./RuleType";
import type { JsonValue } from "./serde_json/JsonValue";

export type Rule = { type: RuleType, index: number, payload: string, proxy: string, size: number, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
